version: "3"
stages:
- test
- build
- deploy
build:
  stage: build
  job_type: lite_image_build
  only:
    branches:
    - .*
    tags:
    - .*
  compile:
    dockerfile_path: /Dockerfile
    build_dir: /
    cache: true
  extract:
  - /tmp/output/dnsdock
  package:
    dockerfile_path: /Dockerfile.package
    build_dir: /
    cache: true
